@startuml
'https://plantuml.com/sequence-diagram

entity 三娃的手
entity 三娃的胳膊
actor 三娃
actor 蝎子精
entity 刀

activate 三娃
activate 三娃的手
activate 三娃的胳膊
activate 蝎子精
activate 刀
蝎子精 -> 刀 : 拿着
三娃 -> 三娃 : 生气
三娃 -> 蝎子精 : 攻击
note left
用三娃的身体
end note
蝎子精 -> 蝎子精 : 跌倒在地上
三娃 -> 三娃 : 笑了
蝎子精 -> 蝎子精 : 从地上爬起来
蝎子精 -> 蝎子精 : 生气
蝎子精 -> 三娃 : 攻击
刀 -> 三娃 : 武器
三娃 -> 刀 : 躲开
三娃 -> 刀 : 攻击
三娃的手 -> 刀 : 武器
刀 -> 刀 : 裂开
蝎子精 -> 蝎子精 : 害怕
蝎子精 -> 刀 : 看了看
蝎子精 -> 蝎子精 : 很生气
三娃 -> 刀 : 攻击
三娃的手 -> 刀 : 武器
刀 -> 刀 : 破洞
蝎子精 -> 刀 : 看了看
三娃 -> 三娃 : 笑得很开心
蝎子精 -> 刀 : 扔掉
destroy 刀
蝎子精 -> 蝎子精 : 非常生气
create entity 蝎子精的钳子
蝎子精 -> 蝎子精的钳子 : 手变成钳子
activate 蝎子精的钳子
蝎子精 -> 三娃的胳膊 : 攻击
蝎子精的钳子 -> 三娃的胳膊 : 武器
三娃 -> 蝎子精 : 告诉
note left
诶，来吧
end note
蝎子精的钳子 -> 蝎子精的钳子 : 裂开
蝎子精 -> 蝎子精 : 非常生气
蝎子精 -> 蝎子精 : 钳子再生
三娃 -> 蝎子精 : 告诉
note left
再来啊
end note
蝎子精 -> 三娃的胳膊 : 攻击
蝎子精的钳子 -> 三娃的胳膊 : 武器
蝎子精 -> 蝎子精 : 感到疼痛
三娃 -> 三娃 : 笑得很开心
蝎子精 -> 蝎子精 : 极度愤怒
蝎子精 -> 蝎子精的钳子 : 钳子变成手
deactivate 蝎子精的钳子
蝎子精 -> 蝎子精 : 化作一阵黑风
蝎子精 -> 蝎子精 : 跑了
deactivate 蝎子精
三娃 -> 蝎子精 : 告诉
note left
你想跑？
end note
三娃 -> 蝎子精 : 追赶
三娃 -> 蝎子精 : 告诉
note left
哪里走！
end note

@enduml