@startuml
title 时序图
==进入洞穴==
大娃 -> 蛇妖:妖怪，还我爷爷。
蛇妖 -> 蛇妖:转眼睛
蛇妖 -> 大娃:好啊，你倒是个孝子，我是你妈。
大娃 -> 蛇妖:呸，不要脸
蝎妖 -> 蝎妖:高兴的笑
大娃 -> 蝎妖:不放人就砸了你的洞
蝎妖 -> 蝎妖:愤怒的笑
蝎妖 -> 大娃:攻击（物理）
大娃 -> 蝎妖:防御
蝎妖 -> 蝎妖:愤怒
蛇妖 -> 大娃:攻击（魔法）
大娃 -> 蛇妖:防御

@enduml 