@startuml timeline
actor 鳄鱼
actor 青蛇大王
actor 青蛙精
actor 虾精
actor 老鼠精
entity 七星丹

鳄鱼 -[#Gray]> 青蛇大王:嗯 七星丹 啊 七星丹 大王 你看这七星丹练成了!
七星丹 -[#Green]> 七星丹: *闪*闪*发*光*
青蛇大王 -[#Blue]> 青蛇大王: 嘿嘿
青蛙精 -[#Gray]>青蛇大王: 恭喜大王，贺喜大王，七星丹终于练~练~练~练~练成了。
虾精 -[#Blue]> 虾精 : 哎嘿
老鼠精 -[#Blue]> 老鼠精 : 哎嘿
七星丹 -[#Green]> 七星丹: *闪*闪*发*光*
青蛙精 -[#Pink]> 青蛙精: 蹑手蹑脚走到七星丹前
青蛙精 -[#Pink]> 青蛙精: 拿起七星丹
青蛙精 -[#Pink]> 青蛙精: 吹气
青蛙精 -[#HotPink]> 青蛙精: 眼珠飞快转动
青蛙精 -[#Pink]> 青蛙精: 向青蛇大王呈上七星丹。
青蛇大王 -[#Blue]> 青蛇大王: 这七星丹可来之不易啊，我姐姐姐夫为了它，捞了个粉身碎骨，今天深仇已报，大功告成。我借此吉庆之时，告慰姐姐姐夫的在天之灵。
青蛇大王 -[#HotPink]> 青蛇大王: 泪流满面...
青蛙精 -[#Gray]> 青蛇大王: 这葫芦兄弟在劫难逃，今天总算被大王练成了七星神丹，这是老天有眼，也是大王的鸿福。大王吃了这七星丹将与日月共存，无敌天下。小的们靠大王的神威也有好日子过了~
@enduml