@startuml
actor 大娃 #red
actor 蛇精 #black
actor 蝎子精 #blue
actor 蜘蛛小兵 #yellow
蝎子精->蝎子精:大笑
note right:哈哈！嘿嘿嘿嘿...
大娃<-大娃:苏醒
蛇精-->大娃:告诉
note right:喂，葫芦娃，怎么样啊，做了个好梦吧
大娃<-大娃:翻白眼
蛇精-->大娃:告诉
note right:我告诉你，你的丹田已经被我封住了，你就别想再撒野了
蜘蛛小兵->蜘蛛小兵:拉蛛网
蛇精-->大娃:告诉
note right:啊我真不想杀掉你，你又楞又蛮又可爱
大娃<-大娃:翻白眼
蛇精-->大娃:告诉
note right:真讨人喜欢，你只要愿意啊，
蛇精->大娃:亲吻×2
大娃->大娃:震惊
note left:睁大眼睛嘴巴
蛇精-->大娃:告诉
note right:你就做我的娃子吧
蝎子精->蝎子精:大笑
note right:嘿嘿嘿嘿...
大娃-[#red]>蛇精:造成伤害
note left:吐口水
大娃-[#red]>蝎子精:造成伤害
note left:吐口水
蛇精->蛇精:大叫
note right:啊嗷!
蝎子精->蝎子精:大叫
note right:啊啊啊...
大娃->大娃:大笑
note left:哈哈哈哈哈哈哈哈哈
蝎子精->蝎子精:发怒
note right:哇呀呀呀呀呀呀...
蛇精->蛇精:发怒
note right:呀呀呀呀！你!你你你...
蝎子精-[#red]>大娃:发动攻击
note right:扔出铁叉
大娃->大娃:震惊
note left:睁大眼睛嘴巴
@enduml