@startuml
Class Creature{
	- String name;
	+ void speakTo(Creature creature1, Creature creature2, String sentence)
	+ void speakTo(Creature creature, String sentence)
	+ void listenFrom(String HName, String sentence)
	+ void fireImpact()
}

Class ScorpionEssence{
	+ void yell()
	+ void praise()
}

Class SnakeEssence{
	+ void yell()
}

Class CommonMonster{
	- String place
	+ String place()
	+ void runAway()
	+ void fireImpact()
}

Class HuoWa{
	+ void rollEyes()
	+ void disCover(CommonMonster CM)
	+ void fireTo(Creature creature)
	+ void fireTo(InertMatter IM)
}

Class ShuiWa{
}

Class InertMatter{
	- String name;
	+ String name();
	+ void fireImpact();
}

Class CaveTop{
	- boolean bright
	+ void light()
	+ void fireImpact()
}

Class Cup{
	- boolean hot
	+ void  CupHot()
	+ void fireImpact()
}

Creature <|-- ScorpionEssence
Creature <|-- CommonMonster
Creature <|-- ScorpionEssence
Creature <|-- SnakeEssence
Creature <|-- HuoWa
Creature <|-- ShuiWa
InertMatter <|-- CaveTop
InertMatter <|-- Cup

@enduml